### ISSUE TITLE
iOS 9 scrolling performance

### ISSUE THREAD

**Issue by kartikthapar** [chiunam/CTAssetsPickerController#151]
I am not sure this issue exists on previous versions of iOS; but simply running the demo application on iOS 9 with only about 200 photos seems to create some scrolling issues. The scrolling isn't as smooth as you would expect. Can somebody else verify this?

**Comment by chiunam** [comment]
Hi @kartikthapar, this picker has changed to photo frameworks and auto layout since v3 that requires more processing power for creating the thumbnails. Prefetching and caching of thumbnails have also been implemented for improving scrolling performance. Thought it cannot meet the same speed of iOS's Photos.app, it can reach 5x fps in average on my iPhone 6 with more than 1000 photos.

![screen_shot_2015-09-21_at_4_17_01_pm](https://cloud.githubusercontent.com/assets/327273/9987658/59b2b85e-607c-11e5-9824-769324c8f739.png)

If you really need to take care older devices, you might consider to use v2.

**Comment by chiunam** [comment]
@kartikthapar, there is new discussion about scrolling performance in #189. Please help to test if you are free.
