### ISSUE TITLE
Is there a way to deselect asset and update assets view from my app?

### ISSUE THREAD

**Issue by tomoyuki28jp** [chiunam/CTAssetsPickerController#81]
Following code works for the first time, but next time when I present CTAssetsPickerController, just a blank view is shown.

    let asset = assets.objectAtIndex(index) as ALAsset
    imagePicker.deselectAsset(asset)
    NSNotificationCenter.defaultCenter().postNotificationName(
        CTAssetsPickerSelectedAssetsChangedNotification, object: nil)
    NSNotificationCenter.defaultCenter().postNotificationName(
        ALAssetsLibraryChangedNotification, object: nil)

**Comment by tomoyuki28jp** [comment]
I found a solution.

(1) Make this change in CTAssetsPickerController
 https://github.com/tomoyuki28jp/CTAssetsPickerController/commit/2996372693a32e7015f985ab18e9d59f061234ad

(2) And following code just works fine.

    let asset = assets.objectAtIndex(index) as ALAsset
    imagePicker.deselectAsset(asset)
    presentViewController(imagePicker, animated: true, completion: nil)

**Comment by chiunam** [comment]
@tomoyuki28jp Just want to make it clear.  You want to deselect asset programmatically but the `collectionView` did not update accordingly. Is it your issue? 

I did a brief test but did not find the *blank view* issue you mentioned in the very first comment. Instead, I found that the `collectionView` did not update after calling `de/selectAsset` methods. If that is the case, I just push a fix at e89b3b8a564edd96a53980695ad7505e7b870b97. 

BTW, just also want to clarify that you need not post the `CTAssetsPickerSelectedAssetsChangedNotification` when calling `deselectAsset` method. It has already done for you. And you need not post `ALAssetsLibraryChangedNotification` neither.  In most cases, you just need to observe `ALAssetsLibraryChangedNotification` instead of posting it.

**Comment by tomoyuki28jp** [comment]
@chiunam Sorry, I'm late to reply. I've tried the latest code from the master branch and it works as I expected! Thanks a lot for your great work and support!

**Comment by chiunam** [comment]
@tomoyuki28jp That's great.
